### ISSUE TITLE
Group shapes into categories and set limit to duration

### ISSUE THREAD

**Issue by AnitaLi-0371** [UBC-MDS/out_of_this_world#10]
Hi everyone, I run into another problem and need your advice on this. There are 18 "unique" shapes in our data set, after removing invalid duration, which are:

` print(ufo_summary$Shape)
 [1] "Chevron"   "Cigar"     "Circle"    "Cone"      "Cross"     "Cylinder" 
 [7] "Diamond"   "Disk"      "Egg"       "Fireball"  "Flash"     "Formation"
[13] "Light"     "Oval"      "Rectangle" "Sphere"    "Teardrop"  "Triangle" `

We need to group them into fewer categories, because some of them only have less than 10 counts. 

Duration is another issue because they have really large range (i.e from a few seconds to over 5000 sec), which is hard to show on the graph. Any advice? Should we take count instead of mean of medium?

**Comment by JacobMcFarlane** [comment]
For the duration plot I'd maybe go with showing the actual points or a violin plot and potentially tossing outliers depending on how many there are. I think we're looking at sort of a power law distribution thing here so another option (if it's not just a couple of outliers mucking things up for us) would be taking the log of time. 

Totally agree on the binning- 18 or so groups will likely make our lives hard going forward. A couple of options might be to change our question- we could compare one group to the rest (an option might be "circle" since that's sort of the classic UFO shape).  Alternatively we could bin by curvy (so like cigar, circle, cone, cylinder etc) and then everything else or curvy, straight lines) and "other"  since I'm not sure what we'd do with fireball.

**Comment by spentelow** [comment]
Another option would be to add Washington State into the mix which would add about 4100 entries.  Would make for more cleaning though...

**Comment by chiragrank** [comment]
I have updated the downloaded script enabling it to get data from multiple states. We can now go ahead with the analysis data of Washington state added in the data and check the distribution.
