### ISSUE TITLE
Some Data Suggestions

### ISSUE THREAD

**Issue by JacobMcFarlane** [UBC-MDS/out_of_this_world#2]
Hello team!

I was thinking a github issue would be a good place for a discussion around which dataset we want to choose for this project. 

A couple of possibilities I was looking at:
[This data set](https://ingeniumcanada.org/collection-research/artifact-open-data-set-mash-up) has information on the size, shape and year of different artifacts in the collections of a couple different Canadian museums. We could ask a question along the lines of "Do these museums elect to preserve more stuff from certain years?" There's a sort of interesting philosophical slant about what's worth preserving for future generations that I think is kind of cool.

[There was also a whole database](http://www.nuforc.org/webreports.html) of UFO sightings here with time, location, duration of sighting, and a summary of each sighting. We could ask something along the lines of "Where in BC reports the most UFO sightings?" It's a little silly but it might be fun to work with. 

Let me know what you think! I'm totally open to other options, just wanted to throw these out there since they caught my eye.

**Comment by AnitaLi-0371** [comment]
Hello everyone,

I think Jacob provide some great examples. Just want to add a few more options after reading through past examples - some data from [UCI machine learning repository](https://archive.ics.uci.edu/ml/datasets.php)
- [stock prediction related](https://archive.ics.uci.edu/ml/datasets/CNNpred%3A+CNN-based+stock+market+prediction+using+a+diverse+set+of+variables)
- [flue gas emissions related](https://archive.ics.uci.edu/ml/datasets/Gas+Turbine+CO+and+NOx+Emission+Data+Set)

I have not spent much time digging into those, but these dataset have enough samples and different types of variables so that we can have some research questions etc. Just trying to throw some ideas.

**Comment by chiragrank** [comment]
Hi everyone, Those datasets looks nice! 
Another dataset that we could add to the list for consideration is of the complaints filed to FDA related to food and related stuff. It is available at [CFSAN Adverse Event Reporting System (CAERS) | FDA](https://www.fda.gov/food/compliance-enforcement-food/cfsan-adverse-event-reporting-system-caers) with detailed description along with all the meta data information at [ReadMe](https://www.fda.gov/media/97035/download) The data set looks clean and is in csv format.  We can use it to answer some of the questions like food items that were most reported, common places of reporting.

**Comment by JacobMcFarlane** [comment]
For posterity: we decided on the UFO data set!
